config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root 'posts#index'
  resources :posts do
    resources :comments
  end
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    return unless user.present?
    if user.admin?
      can :manage, :all
      cannot :destroy, User, role: 1
    end
    if user.moderator?
      can :manage, Post
      can :manage, Comment
    end
    can :manage, Post, user_id: user.id
    can :manage, Comment, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_taggable

  validates :text, presence: true
  mount_uploader :image, ImageUploader

  scope :filter_by_author, -> (author) { joins(:user).where(users: { login: author }) }
  scope :filter_by_content, -> (phrase) { where ('text LIKE ?'), "%#{phrase}%" }
  scope :filter_by_address, -> (address) { joins(:user).where('users.address LIKE ?', "%#{address}%") }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :posts, dependent: :destroy
  has_many :comments

  validates :login, :first_name, :last_name, :birthday, :address, :city,
            :state, :country, :zip, :email, presence: true
  validates :zip, numericality: true
  validates :login, uniqueness: { case_sensitive: false }

  geocoded_by :full_address
  before_save :geocode

  enum role: [:moderator, :admin]

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def full_address
    [address, city, state, country].compact.join(', ')
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:login, :first_name,
                                                       :last_name, :birthday,
                                                       :email, :address,
                                                       :city, :state,
                                                       :country, :zip,
                                                       :password, :remember_me])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email,
                                                       :password,
                                                       :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:login, :first_name,
                                                              :last_name,
                                                              :birthday,
                                                              :email, :address,
                                                              :city, :state,
                                                              :country, :zip,
                                                              :password,
                                                              :current_password,
                                                              :remember_me])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource only: :destroy

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build(comment_params)

    if @comment.save
      respond_to do |f|
        f.html { redirect_to post_path(@comment.post) }
        f.js
      end
    else
      redirect_to post_path(params[:post_id]), notice: 'Comment was not saved'
    end
  end

  def destroy
    @comment.destroy

    respond_to do |f|
      f.html { redirect_to post_path(params[:post_id]) }
      f.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  load_and_authorize_resource only: [:edit, :update, :destroy, :show]

  def index
    if params[:search_phrase].present?
      @posts = SearchService.new(params[:search_phrase],
                                 params[:search_param]).filter_by_search_param
    else
      @posts = Post.all
    end
    @posts = @posts.includes(:user, :taggings)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show
    @comments = @post.comments.includes(:user)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to root_path, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Post was successfully destroyed'
  end

  private

  def post_params
    params.require(:post).permit(:text, :user_id, :image,
                                 :tag_list, :search_phrase, :search_param)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      flash[:notice] = 'Facebook signed in successfully.'
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
      flash[:notice] = 'Please, fill this form before start.'
    end
  end

  def failure
    flash[:alert] = 'Facebook log in failed'
    redirect_to new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  load_and_authorize_resource
  skip_authorize_resource only: :index

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed'
  end

  private

  def user_params
    params.require(:user).permit(:login, :first_name, :last_name,
                                 :birthday, :email, :address, :city,
                                 :state, :country, :zip, :role)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_author(post)
    post.user.login
  end

  def comment_author(comment)
    comment.user.login
  end

  def safe_textilize(str)
    return unless str && str.respond_to?(:to_s)
    doc = RedCloth.new(str.to_s)
    doc.filter_html = true
    render_haml(doc.to_html)
  end

  def post_image(post)
    post.image.present? ? post.image.thumb.url : post.image.default_url
  end

  def post_image_for_show_page
    @post.image.blank? ? 'No Image Available' : render_haml(image_tag @post.image)
  end

  private

  def render_haml(code)
    engine = Haml::Engine.new(code)
    engine.render
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def coordinates(user)
    [user.latitude, user.longitude].join(',')
  end

  def full_addr
    "#{@user.zip}, #{@user.country.capitalize}, #{@user.state.capitalize}, #{@user.city.capitalize}, #{@user.address}"
  end
end

app/views/comments/_form.html.haml
%h2 Add a comment:
= form_for([post, post.comments.build], remote: true) do |f|
  .field
    = f.label :body
    %br/
    = f.text_area :body
    %br/
    = f.hidden_field :user_id, value: current_user.id
  .actions
    = f.submit

app/views/comments/create.js.erb
$('#comments').prepend('<%= j render(partial: 'posts/comment', locals: {comment: @comment}) %>')
$('#comment_body').val('');

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to 'Billboard', root_path, class: 'navbar-brand'
  %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavAltMarkup", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse
    .navbar-nav
      = link_to 'Users', users_path, class: "nav-item nav-link"
      = link_to 'Posts', root_path, class: "nav-item nav-link"
      - if user_signed_in?
        = link_to 'My Profile', edit_user_registration_path, class: "nav-item nav-link"
        = link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-item nav-link"
      - else
        = link_to 'Log in', new_user_session_path, class: "nav-item nav-link"
        = link_to 'Sign up', new_user_registration_path, class: "nav-item nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Billboard
    %meta{name: "viewport", content: "width=device-width"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    - flash.each do |message_type, message|
      %div{class: "alert alert-#{message_type}"}
        %button{type: "button", class: "close", "data-dismiss": "alert", "aria-label": "Close"}
          %span{"aria-hidden": "true"} &times;
        = message
    = yield

app/views/posts/_comment.html.haml
%div{:id => "comment_#{comment.id}"}
  .card.w-75
    .card-body
      %small
        Comment by #{comment_author(comment)}
      %p.card-text= comment.body
      %small
        Commented #{distance_of_time_in_words(comment.created_at, Time.now)} ago
      - if can? :manage, comment
        %br/
        = link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: {confirm: "Really delete the comment?"}, class: "btn btn-primary", remote: true

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  %ul
    - @post.errors.full_messages.each do |error|
      %li= error
  .form-group
    = f.label :text, for: "inputText"
    = f.text_area :text, id: :inputText, placeholder: "Text of post", class: "form-control"
    = f.label :image
    = f.file_field :image
    %br/
    = f.label :tag_list, "Tags (separated by commas)"
    = f.text_field :tag_list

  = f.hidden_field :user_id, value: current_user.id
  = f.submit "Create", class: "btn btn-primary"

app/views/posts/edit.html.haml
= render partial: 'form'

app/views/posts/index.html.haml
.card.text-center
  .card-body
    %h5.card-title Find posts
    = form_tag(root_url, method: :get) do
      = text_field_tag 'search_phrase', nil, placeholder: "Text of search"
      = radio_button_tag :search_param, 'by_tag', checked: true
      = label_tag :search_param_by_tag, 'by tag'
      = radio_button_tag :search_param, 'by_author'
      = label_tag :search_param_by_author, 'by author'
      = radio_button_tag :search_param, 'by_content'
      = label_tag :search_param_by_content, 'by content'
      = radio_button_tag :search_param, 'by_address'
      = label_tag :search_param_by_address, 'by address'
      = submit_tag "Find", class: "btn btn-primary"
    %h5.card-title Create post
    = link_to 'Create', new_post_path, class: "btn btn-primary"
- @posts.each_slice(3) do |post1, post2, post3|
  .card-group
    .col-4
      .card
        = image_tag post_image(post1), class: "img card-img-top"
        .card-body
          %h5.card-title
            = post_author(post1)
          %p.card-text
            = truncate(post1.text, :length => 160, separator: ' ')
          = link_to "Show", post_path(post1), class: "btn btn-primary"
          - if can? :manage, post1
            = link_to 'Edit', edit_post_path(post1), class: "btn btn-primary"
            = link_to "Delete", post_path(post1), method: :delete, data: {confirm: "Really delete the post?"}, class: "btn btn-primary"
        .card-footer
          %small.text-muted Tags: #{post1.tag_list}
    - if post2
      .col-4
        .card
          = image_tag post_image(post2), class: "img card-img-top"
          .card-body
            %h5.card-title
              = post_author(post2)
            %p.card-text
              = truncate(post2.text, :length => 160, separator: ' ')
            = link_to "Show", post_path(post2), class: "btn btn-primary"
            - if can? :manage, post2
              = link_to 'Edit', edit_post_path(post2), class: "btn btn-primary"
              = link_to "Delete", post_path(post2), method: :delete, data: {confirm: "Really delete the post?"}, class: "btn btn-primary"
          .card-footer
            %small.text-muted Tags: #{post2.tag_list}
    -if post3
      .col-4
        .card
          = image_tag post_image(post3), class: "img card-img-top"
          .card-body
            %h5.card-title
              = post_author(post3)
            %p.card-text
              = truncate(post3.text, :length => 160, separator: ' ')
            = link_to "Show", post_path(post3), class: "btn btn-primary"
            - if can? :manage, post3
              = link_to 'Edit', edit_post_path(post3), class: "btn btn-primary"
              = link_to "Delete", post_path(post3), method: :delete, data: {confirm: "Really delete the post?"}, class: "btn btn-primary"
          .card-footer
            %small.text-muted Tags: #{post3.tag_list}

app/views/posts/new.html.haml
= render partial: 'form'

app/views/posts/show.html.haml
%div{:id => "image"}
  %strong Image:
  %br
  = post_image_for_show_page
  %br
%strong Text:
%br
%div
  = safe_textilize(@post.text)
%br
- if can? :manage, @post
  %div{:id => "buttons"}
    = link_to 'Edit', edit_post_path(@post)
    |
    = link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Really delete the post?"}
%br
%div{:id => "comments"}
  = render partial: 'posts/comment', collection: @comments.reverse
%div{:id => "new-comments"}
  = render partial: 'comments/form', locals: { post: @post }

app/views/users/edit.html.haml
= form_for(@user) do |f|
  %ul
    - @user.errors.full_messages.each do |error|
      %li= error
  .form-group
    .field
      = f.label :login
      %br/
      = f.text_field :login, autofocus: true, autocomplete: "login"
    .field
      = f.label :first_name
      %br/
      = f.text_field :first_name, autocomplete: "first name"
    .field
      = f.label :last_name
      %br/
      = f.text_field :last_name, autocomplete: "last name"
    .field
      = f.label :birthday
      %br/
      = f.date_field :birthday
    .field
      = f.label :address
      %br/
      = f.text_field :address, autocomplete: "address"
    .field
      = f.label :city
      %br/
      = f.text_field :city, autocomplete: "city"
    .field
      = f.label :state
      %br/
      = f.text_field :state, autocomplete: "state"
    .field
      = f.label :country
      %br/
      = f.text_field :country, autocomplete: "country"
    .field
      = f.label :zip
      %br/
      = f.text_field :zip, autocomplete: "zip"
    .field
      = f.label :email
      %br/
      = f.email_field :email, autofocus: true, autocomplete: "email"
    .field
      = f.label :role
      %br/
      = f.text_field :role
    .actions
      = f.submit "Update"

app/views/users/index.html.haml
- @users.each do |user|
  .card{:style => "width: 18rem;"}
    .card-body
      %h5.card-title
        = user.login
      %p.card-text
        = user.email
      = link_to 'Profile', user_path(user), class: "btn btn-primary"
      - if can? :manage, user
        = link_to 'Edit', edit_user_path(user), class: "btn btn-primary"
      - if can? :destroy, user
        = link_to "Delete", user_path(user), method: :delete, data: {confirm: "Really delete the user?"}, class: "btn btn-primary"

app/views/users/show.html.haml
%h1= @user.full_name
%h2= full_addr
%iframe{:allowfullscreen => "", :frameborder => "0", :height => "640", :src => "https://www.google.com/maps/embed/v1/place?key=#{ENV['GOOGLE']}&q=#{coordinates(@user)}", :style => "border:0", :width => "640"}